"""Update models for incident management

Revision ID: 2590ed93b99a
Revises: 130173f149d7
Create Date: 2024-07-08 12:48:37.065301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2590ed93b99a'
down_revision = '130173f149d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_chat_log_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_reported', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aws_service', sa.String(length=50), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index('ix_incident_date')
        batch_op.create_index(batch_op.f('ix_incident_date_reported'), ['date_reported'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_incident_date_reported'))
        batch_op.create_index('ix_incident_date', ['date'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('aws_service')
        batch_op.drop_column('severity')
        batch_op.drop_column('date_reported')
        batch_op.drop_column('title')

    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_chat_log_timestamp'))
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.drop_column('timestamp')

    op.drop_table('aws_resource')
    # ### end Alembic commands ###
