"""Add instance_type and launch_time to AWSResource

Revision ID: 3e4b9f493ff1
Revises: 2590ed93b99a
Create Date: 2024-07-09 04:32:37.830944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4b9f493ff1'
down_revision = '2590ed93b99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('launch_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_resource', schema=None) as batch_op:
        batch_op.drop_column('launch_time')
        batch_op.drop_column('instance_type')

    # ### end Alembic commands ###
