"""Add Role model
Revision ID: 93391aa2a459
Revises: 3e4b9f493ff1
Create Date: 2024-07-09 21:41:09.740032
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '93391aa2a459'
down_revision = '3e4b9f493ff1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_role_id', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')
    # ### end Alembic commands ###
